version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/build/
    overwrite: true
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: startup.sh # 배포 이후에 실행될 스크립트이다.
      timeout: 60
      runas: ec2-user
  #BeforeInstall:
  #  - location: deploy-before.sh
  #    runas: ec2-user
  #ApplicationStart:
  #  - location: deploy.sh
  #    runas: ec2-user