server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    #url: jdbc:h2:mem:test;MODE=MySQL
    url: jdbc:mariadb://localhost:3306/kakao
    #driver-class-name: org.h2.Driver
    #driver-class-name: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  rdis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

    #hibernate:
    #  ddl-auto: create
    #show-sql: true
    #properties:
    #  hibernate:
    #    format_sql: true
    #  default_batch_fetch_size: 100
    #open-in-view: false

  output:
    ansi:
      enabled: always

logging:
  level:
    '[com.example.kakao]': DEBUG
    '[org.hibernate.type]': TRACE

file:
  path: ./images/